# Generated by Django 2.1.5 on 2019-02-14 19:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('start_time', models.TimeField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('location', models.CharField(max_length=200)),
                ('location_details', models.TextField(max_length=2000)),
                ('cost', models.FloatField()),
                ('age_requirement', models.IntegerField()),
                ('link', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('event_coordinator_name', models.CharField(max_length=200)),
                ('event_coordinator_email', models.EmailField(max_length=254)),
                ('image_link', models.CharField(max_length=200)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
