# Generated by Django 2.1.5 on 2019-03-12 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
