# Generated by Django 2.1.5 on 2019-03-11 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20190214_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_details',
            field=models.TextField(default='Default Event Details', max_length=2000),
            preserve_default=False,
        ),
    ]
