# Generated by Django 2.1.5 on 2019-03-12 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20190312_0235'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=2000)),
                ('start_time', models.TimeField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('location', models.CharField(max_length=200)),
                ('location_details', models.TextField(max_length=2000)),
                ('event_details', models.TextField(max_length=2000)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('age_requirement', models.IntegerField()),
                ('link', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('event_coordinator_name', models.CharField(max_length=200)),
                ('event_coordinator_email', models.EmailField(max_length=254)),
                ('image_link', models.CharField(max_length=200)),
            ],
        ),
    ]
