# Generated by Django 2.1.5 on 2019-03-12 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_defaultevent'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DefaultEvent',
            new_name='HomePageEvent',
        ),
    ]
