# Generated by Django 2.1.5 on 2019-03-12 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20190312_0404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_details',
        ),
        migrations.RemoveField(
            model_name='homepageevent',
            name='event_details',
        ),
    ]
