# Generated by Django 2.1.5 on 2019-04-09 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20190312_0457'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepageevent',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
