# Generated by Django 2.1.5 on 2019-04-11 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_homepageevent_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
    ]
