# Generated by Django 2.1.5 on 2019-04-11 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20190411_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepageevent',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
    ]
