# Generated by Django 2.1.7 on 2019-04-25 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_auto_20190411_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepageevent',
            name='age_requirement',
            field=models.CharField(max_length=200),
        ),
    ]
