# Generated by Django 2.1.5 on 2019-04-25 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_homepageevent_event_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image_link',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='event',
            name='link',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='homepageevent',
            name='image_link',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='homepageevent',
            name='link',
            field=models.CharField(max_length=2000),
        ),
    ]
