# Generated by Django 2.1.5 on 2019-03-05 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20190304_2349'),
        ('news', '0004_auto_20190223_2110'),
    ]

    operations = [
    ]
