# Generated by Django 2.1.5 on 2019-03-05 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='email_activated',
            field=models.BooleanField(default=False),
        ),
    ]
