# Generated by Django 2.1.5 on 2019-03-07 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_member_email_activated'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='user_salt',
            field=models.CharField(default=0, max_length=32),
        ),
    ]
